#include <verilated.h>          // Defines common routines
#include "Vdff.h"

#include "verilated_vcd_c.h"

#include <iostream>
#include <string>
#include <cstdlib>
#include <cstdio>

Vdff *uut;                     // Instantiation of module
vluint64_t main_time = 0;       // Current simulation time

double sc_time_stamp () {       // Called by $time in Verilog
    return main_time;           // converts to double, to match
    // what SystemC does
}

// now that this is in cpp instead of verilog, you can write handy functions like this
void fullClockCycle(Vdff* uut, VerilatedVcdC* tfp, vluint64_t* main_time) {
    for (int i = 0; i < 2; ++i) {
        uut->clk = !(uut->clk);
        *main_time = *main_time + 1;
        uut->eval();
        if (tfp != nullptr) {
            tfp->dump (*main_time);
        }
    }
}

int main(int argc, char** argv)
{
    // turn on trace or not?
    bool vcdTrace = true;
    VerilatedVcdC* tfp = NULL;

    Verilated::commandArgs(argc, argv);   // Remember args
    uut = new Vdff;   // Create instance

    uut->eval();
    uut->eval();

    if (vcdTrace)
    {
        Verilated::traceEverOn(true);

        tfp = new VerilatedVcdC;
        uut->trace(tfp, 99);

        std::string vcdname = argv[0];
        vcdname += ".vcd";
        std::cout << vcdname << std::endl;
        tfp->open(vcdname.c_str());
    }

    // PUT YOUR TEST CODE HERE
    uut->clk = 0;
    
    uut->d = 0;
    uut->rst = 0;
    fullClockCycle(uut, tfp, &main_time); // nothing happens until you call uut->eval() (called in fullClockCycle)

    uut->d = 1;
    fullClockCycle(uut, tfp, &main_time);

    uut->rst = 1;
    fullClockCycle(uut, tfp, &main_time);

    fullClockCycle(uut, tfp, &main_time); // one more for visibility

    // note that you can also reach deep into a module's submodules to set values. 
    // Look in the V$MODULE.h file generated by Verilator in obj_dir for the names of the individual regs/ wires
    
    // END TEST CODE

    uut->final();               // Done simulating

    if (tfp != NULL)
    {
        tfp->close();
        delete tfp;
    }

    delete uut;

    return 0;
}

